<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace CBFranFinance3x\Event;

use CBFranFinance3x\Event\Base\CBFranFinance3xEvents as BaseCBFranFinance3xEvents;

/**
 * Class CBFranFinance3xEvents
 * @package CBFranFinance3x\Event
 * @author TheliaStudio
 */
class CBFranFinance3xEvents extends BaseCBFranFinance3xEvents
{
}
