<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace CBFranFinance3x\Form;

use CBFranFinance3x\Form\Base\CBFranFinance3xConfigForm as BaseCBFranFinance3xConfigForm;

/**
 * Class CBFranFinance3xConfigForm
 * @package CBFranFinance3x\Form\Base
 */
class CBFranFinance3xConfigForm extends BaseCBFranFinance3xConfigForm
{
    public function getTranslationKeys()
    {
        return array(
            "authentication_key" => "Authentication key",
            "customize_code" => "Customize code",
            "minimum_price" => "Minimum price",
            "maximum_price" => "Maximum price",
        );
    }
}
