<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace CBFranFinance3x\Event\Base;

/**
 * Class CBFranFinance3xEvents
 * @package CBFranFinance3x\Event\Base
 * @author TheliaStudio
 */
class CBFranFinance3xEvents
{
}
