<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace CBFranFinance3x\Controller;

use CBFranFinance3x\Controller\Base\CBFranFinance3xConfigController as BaseCBFranFinance3xConfigController;

/**
 * Class CBFranFinance3xConfigController
 * @package CBFranFinance3x\Controller
 */
class CBFranFinance3xConfigController extends BaseCBFranFinance3xConfigController
{
}
